#!/bin/bash

echo "What is your name traveller"
read traveller

sleep 1
echo ""

until [[ $race == "human" ]] || [[ $race == "elf" ]] || [[ $race == "dwarf" ]]; do

echo "Greetings $traveller, may I ask where you orignate from?"
read race

	case $race in
		human ) echo "Oh so you're a human"
		;;
		elf ) echo "An elf hmm"
		;;
		dwarf ) echo "A Dwarf, rare to see one out of the moutians"
		;;
		* ) echo "I'm sorry traveller, this race doesn't exist in this world"
		;;
	esac 
done 

sleep 1
echo ""

until [[  $weapon == "sword" ]] || [[ $weapon == "spear" ]] || [[ $weapon == "dagger" ]]; do

echo "Pick a weapon:"
read weapon 

	case $weapon in 
		sword ) echo "You picked the sword"
		;;
		spear ) echo "You picked the spear"
		;;
		dagger ) echo "You picked the dagger"
		;;
		* ) echo "Your fun is wrong"
		;;
	esac 
done 
